default_language_version:
  python: python3.13

ci:
  autoupdate_schedule: monthly

exclude: |
  (?x)^(
    \.venv/|
    venv/|
    \.mypy_cache/|
    \.ruff_cache/|
    \.pytest_cache/|
    .*/migrations/|
    .*/node_modules/
  )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        name: ruff (lint + fix)
        args: [--fix]
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: black (format)
        stages: [pre-commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (imports)
        args: ["--profile=black"]
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy
        args: ["--config-file", "pyproject.toml"]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest-pre-push
        name: pytest (pre-push)
        entry: bash -lc "pytest -q"
        language: system
        pass_filenames: false
        stages: [pre-push]
