default_language_version:
  python: python3.13

ci:
  autoupdate_schedule: monthly

files: ^backend/
exclude: |
  (?x)^(
    backend/.venv/|
    backend/venv/|
    backend/.mypy_cache/|
    backend/.ruff_cache/|
    backend/.pytest_cache/|
    backend/.tox/|
    backend/.git/|
    backend/.eggs/|
    backend/build/|
    backend/dist/|
    backend/.*/migrations/|
    .*/node_modules/
  )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        name: ruff (lint + fix)
        args: [--fix]
        additional_dependencies: []
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: black (format)
        stages: [commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (imports)
        args: ["--profile=black"]
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy (django)
        args: ["--config-file", "backend/pyproject.toml"]
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
        stages: [commit]

  - repo: local
    hooks:
      - id: pytest-pre-push
        name: pytest (pre-push)
        entry: bash -lc "cd backend && pytest -q"
        language: system
        pass_filenames: false
        stages: [push]
