from abc import ABC, abstractmethod
from datetime import date
from typing import List, Optional
from .models import Paciente

class PacienteRepository(ABC):
    @abstractmethod
    def list_all(self, only_active: bool = True) -> List[Paciente]: ...
    @abstractmethod
    def add(self, nome: str, email: str, telefone: str, data_entrada: date) -> Paciente: ...
    @abstractmethod
    def find_by_id(self, pid: str) -> Optional[Paciente]: ...
    @abstractmethod
    def registrar_pagamento(self, pid: str, data_pag: date) -> Paciente: ...
    @abstractmethod
    def list_due_on(self, when: date) -> List[Paciente]: ...
