name: Daily Reminders
on:
  schedule:
    - cron: "0 12 * * *"  # 09:00 BRT ≈ 12:00 UTC
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Write credentials.json
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
      - env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SHEETS_WORKSHEET: Pacientes
          GOOGLE_CREDENTIALS_FILE: credentials.json
        run: PYTHONPATH=. python send_reminders.py
