name: Daily Reminders

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -r requirements.txt
          # Garantir que os imports "from src..." funcionem
          echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run reminder script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          # SMTP
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_USE_TLS: "true"

          LOG_LEVEL: INFO
        run: |
          PYTHONPATH=. python src/utils/send_reminders.py
